---
version: '3.8'

secrets:
  gf-admin-password:
    file: ./secrets/gf_admin_password

services:
  grafana:
    env_file: ./grafana_env
    environment:
    - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/gf-admin-password
    depends_on:
    - loki
    - prometheus
    image: grafana/grafana:9.4.7
    ports:
    - 3000:3000
    restart: always
    secrets:
    - gf-admin-password
    volumes:
    - grafana-data:/var/lib/grafana

  loki:
    command:
    - "-config.file=/etc/loki/local-config.yaml"
    image: grafana/loki:2.8.0
    ports:
    - 3100:3100
    restart: always
    volumes:
    # - ./loki-config.yaml:/etc/loki/config.yaml:ro
    - loki-data:/loki

  prometheus:
    command:
    #   - '--storage.local.retention=72h'
    #   - '--storage.local.memory-chunks=524288'
    - '--config.file=/etc/prometheus/prometheus.yaml'
    #   - '--alertmanager.url=http://alertmanager:9093'
    image:  prom/prometheus:v2.43.0
    restart: always
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    - prometheus-data:/prometheus
    ports:
    - 9090:9090
    restart: always

volumes:
  grafana-data:
  loki-data:
  prometheus-data:
