---
version: '3.8'

services:
  cadvisor:
    image: zcube/cadvisor:v0.45.0
    ports:
    - 8080:8080
    restart: always
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter:v1.5.0
    ports:
    - 9100:9100
    restart: always
    volumes:
    - /proc:/host/proc
    - /sys:/host/sys
    - /:/rootfs

  promtail:
    command: -config.file=/etc/promtail/config.yaml
    image: grafana/promtail:2.8.0
    restart: always
    volumes:
    - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
    - /var/log:/var/log
