---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.13:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/daemon.log
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/messages
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/syslog

- job_name: secure
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/secure
